{{- if .Values.env.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-env-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    name: {{ .Values.jobName }}
type: Opaque
data:
{{- range $key, $value :=  .Values.env.secret }}
  {{ $key }}: {{ $value | toString | b64enc }}
{{- end }}
{{- end }}